services:
  - type: web
    name: sanjar-patir-tizimi
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_XoJBhMVNjQ23@ep-bitter-lab-ab82thfg-pooler.eu-west-2.aws.neon.tech/neondb
